//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_a.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactTbl
    {
        public string uye_ad { get; set; }
        public string uye_mail { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public int message_id { get; set; }
    
        public virtual contactTbl contactTbl1 { get; set; }
        public virtual contactTbl contactTbl2 { get; set; }
    }
}
