//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_a.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kayipTbl
    {
        public int kayip_id { get; set; }

        public int uye_id { get; set; }


        [Display(Name = " ")]
        public string kayip_ad { get; set; }


        [Display(Name = " ")]
        public string kayip_turu { get; set; }


        [Display(Name = " ")]
        public string kayip_cinsiyet { get; set; }


        [Display(Name = " ")]
        public int kayip_yas { get; set; }


        [Display(Name = " ")]
        public string kayip_renk { get; set; }

        [Display(Name = " ")]
        public string kayip_il { get; set; }

        [Display(Name = " ")]
        public string kayip_tarihi { get; set; }

        [Display(Name = " ")]
        public string resim { get; set; }

        [Display(Name = " ")]
        public string kayip_aciklama { get; set; }
    }
}
