//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_a.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siteDbEntities6 : DbContext
    {
        public siteDbEntities6()
            : base("name=siteDbEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactTbl> contactTbl { get; set; }
        public virtual DbSet<imageTbl> imageTbl { get; set; }
        public virtual DbSet<uyeTbl> uyeTbl { get; set; }
        public virtual DbSet<kayipTbl> kayipTbl { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<blogTbl> blogTbl { get; set; }
    }
}
